### ISSUE TITLE
The override key has priority over the controls of the menu (A9LH)

### ISSUE THREAD

**Issue by capito27** [Cpasjuste/CtrBootManager#11]
hi, whenever i boot into the A9LH version and skip the autoboot, if i set key A to decrypt9 and try to launch aureinand manually, decrypt9 will start instead, i assume the same happens with the arrows.

**Comment by Cpasjuste** [comment]
Hi capito,

I'll take a look very soon, thanks for the report.

**Comment by Cpasjuste** [comment]
Hi,

I think the problem should be solved in latest builds.
