### ISSUE TITLE
DS Mode shutdown (a9lx)

### ISSUE THREAD

**Issue by jixunmoe** [Cpasjuste/CtrBootManager#21]
1. Enter ds mode
2. Press power button
3. Expected: Shutdown screen show up.  
   Actual: Boot Manager screen show up.

**Comment by dogtopus** [comment]
This is an expected behavior since 3DS reboots itself in order to display the "Software Closed" screen when exiting from TWL mode.
A workaround of this would be enabling autoboot on CtrBootManager and let it automatically load the CFW you are using.

**Comment by jixunmoe** [comment]
Hmm... okey then :D
